### one dimensional array

In [3]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


### Multi dimensional array

In [4]:
m_arr = np.array([[1,2,3],[4,5,6]])
print(m_arr)

[[1 2 3]
 [4 5 6]]


### N dimensional array can create

In [5]:
m_arr2 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(m_arr2)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
